// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pluginapi/proto/tool.proto

package pluginapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty message for RPCs that don't need parameters
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{0}
}

// ToolDefinition represents a generic, provider-agnostic tool definition.
// This format works with any LLM provider (OpenAI, Claude, Ollama, etc.)
// and will be automatically translated to provider-specific formats by the server.
type ToolDefinition struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ParametersJson string                 `protobuf:"bytes,3,opt,name=parameters_json,json=parametersJson,proto3" json:"parameters_json,omitempty"` // JSON-encoded JSON Schema for parameters
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{1}
}

func (x *ToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDefinition) GetParametersJson() string {
	if x != nil {
		return x.ParametersJson
	}
	return ""
}

// CallRequest contains the arguments for calling a tool
type CallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArgsJson      string                 `protobuf:"bytes,1,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"` // JSON-encoded tool arguments
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{2}
}

func (x *CallRequest) GetArgsJson() string {
	if x != nil {
		return x.ArgsJson
	}
	return ""
}

// CallResponse contains the result of a tool call
type CallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultJson    string                 `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"` // JSON-encoded result on success
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                             // Error message on failure (empty on success)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{3}
}

func (x *CallResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *CallResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// VersionResponse contains the plugin version
type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{4}
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// AgentContextRequest provides current agent information to the plugin
type AgentContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                     // Agent name (e.g., "default", "my-agent")
	ConfigPath    string                 `protobuf:"bytes,2,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`       // Path to agent's config.json
	SettingsPath  string                 `protobuf:"bytes,3,opt,name=settings_path,json=settingsPath,proto3" json:"settings_path,omitempty"` // Path to agent's agent_settings.json
	AgentDir      string                 `protobuf:"bytes,4,opt,name=agent_dir,json=agentDir,proto3" json:"agent_dir,omitempty"`             // Path to agent's directory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentContextRequest) Reset() {
	*x = AgentContextRequest{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentContextRequest) ProtoMessage() {}

func (x *AgentContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentContextRequest.ProtoReflect.Descriptor instead.
func (*AgentContextRequest) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{5}
}

func (x *AgentContextRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentContextRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *AgentContextRequest) GetSettingsPath() string {
	if x != nil {
		return x.SettingsPath
	}
	return ""
}

func (x *AgentContextRequest) GetAgentDir() string {
	if x != nil {
		return x.AgentDir
	}
	return ""
}

// SettingsResponse contains plugin settings as JSON
type SettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SettingsJson  string                 `protobuf:"bytes,1,opt,name=settings_json,json=settingsJson,proto3" json:"settings_json,omitempty"` // JSON-encoded settings
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                                   // Error message on failure (empty on success)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingsResponse) Reset() {
	*x = SettingsResponse{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsResponse) ProtoMessage() {}

func (x *SettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsResponse.ProtoReflect.Descriptor instead.
func (*SettingsResponse) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{6}
}

func (x *SettingsResponse) GetSettingsJson() string {
	if x != nil {
		return x.SettingsJson
	}
	return ""
}

func (x *SettingsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ProtoConfigVariable describes a single configuration variable (protobuf version)
type ProtoConfigVariable struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Key              string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type             string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // "string", "int", "filepath", "dirpath", "password", etc.
	Required         bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	DefaultValueJson string                 `protobuf:"bytes,6,opt,name=default_value_json,json=defaultValueJson,proto3" json:"default_value_json,omitempty"` // JSON-encoded default value (optional)
	Validation       string                 `protobuf:"bytes,7,opt,name=validation,proto3" json:"validation,omitempty"`                                       // Validation rules (optional)
	Options          []string               `protobuf:"bytes,8,rep,name=options,proto3" json:"options,omitempty"`                                             // List of valid options (optional)
	Placeholder      string                 `protobuf:"bytes,9,opt,name=placeholder,proto3" json:"placeholder,omitempty"`                                     // Placeholder text (optional)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProtoConfigVariable) Reset() {
	*x = ProtoConfigVariable{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoConfigVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoConfigVariable) ProtoMessage() {}

func (x *ProtoConfigVariable) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoConfigVariable.ProtoReflect.Descriptor instead.
func (*ProtoConfigVariable) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{7}
}

func (x *ProtoConfigVariable) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ProtoConfigVariable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProtoConfigVariable) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProtoConfigVariable) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProtoConfigVariable) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ProtoConfigVariable) GetDefaultValueJson() string {
	if x != nil {
		return x.DefaultValueJson
	}
	return ""
}

func (x *ProtoConfigVariable) GetValidation() string {
	if x != nil {
		return x.Validation
	}
	return ""
}

func (x *ProtoConfigVariable) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ProtoConfigVariable) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

// ConfigVariablesResponse contains the list of required config variables
type ConfigVariablesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigVars    []*ProtoConfigVariable `protobuf:"bytes,1,rep,name=config_vars,json=configVars,proto3" json:"config_vars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigVariablesResponse) Reset() {
	*x = ConfigVariablesResponse{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigVariablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigVariablesResponse) ProtoMessage() {}

func (x *ConfigVariablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigVariablesResponse.ProtoReflect.Descriptor instead.
func (*ConfigVariablesResponse) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigVariablesResponse) GetConfigVars() []*ProtoConfigVariable {
	if x != nil {
		return x.ConfigVars
	}
	return nil
}

// ValidateConfigRequest contains configuration to validate
type ValidateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    string                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"` // JSON-encoded configuration map
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigRequest) Reset() {
	*x = ValidateConfigRequest{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigRequest) ProtoMessage() {}

func (x *ValidateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigRequest.ProtoReflect.Descriptor instead.
func (*ValidateConfigRequest) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateConfigRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

// InitializeConfigRequest contains configuration for initialization
type InitializeConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    string                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"` // JSON-encoded configuration map
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeConfigRequest) Reset() {
	*x = InitializeConfigRequest{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeConfigRequest) ProtoMessage() {}

func (x *InitializeConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeConfigRequest.ProtoReflect.Descriptor instead.
func (*InitializeConfigRequest) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{10}
}

func (x *InitializeConfigRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

// ConfigResponse contains the result of config operations
type ConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Error message on failure (empty on success)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{11}
}

func (x *ConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Maintainer represents a single plugin maintainer/contributor
type Maintainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                 // Full name
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`               // Contact email
	Organization  string                 `protobuf:"bytes,3,opt,name=organization,proto3" json:"organization,omitempty"` // Organization affiliation
	Website       string                 `protobuf:"bytes,4,opt,name=website,proto3" json:"website,omitempty"`           // Personal/project website
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`                 // "author", "maintainer", "contributor"
	Primary       bool                   `protobuf:"varint,6,opt,name=primary,proto3" json:"primary,omitempty"`          // Is this the primary/original author?
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Maintainer) Reset() {
	*x = Maintainer{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Maintainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Maintainer) ProtoMessage() {}

func (x *Maintainer) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Maintainer.ProtoReflect.Descriptor instead.
func (*Maintainer) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{12}
}

func (x *Maintainer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Maintainer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Maintainer) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *Maintainer) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *Maintainer) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Maintainer) GetPrimary() bool {
	if x != nil {
		return x.Primary
	}
	return false
}

// Platform represents a supported operating system and its architectures
type Platform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`                       // Operating system (e.g., "darwin", "linux", "windows")
	Architectures []string               `protobuf:"bytes,2,rep,name=architectures,proto3" json:"architectures,omitempty"` // Supported architectures (e.g., "amd64", "arm64")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Platform) Reset() {
	*x = Platform{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Platform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Platform) ProtoMessage() {}

func (x *Platform) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Platform.ProtoReflect.Descriptor instead.
func (*Platform) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{13}
}

func (x *Platform) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Platform) GetArchitectures() []string {
	if x != nil {
		return x.Architectures
	}
	return nil
}

// Requirements represents plugin dependencies and version requirements
type Requirements struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinOriVersion string                 `protobuf:"bytes,1,opt,name=min_ori_version,json=minOriVersion,proto3" json:"min_ori_version,omitempty"` // Minimum ori-agent version required
	Dependencies  []string               `protobuf:"bytes,2,rep,name=dependencies,proto3" json:"dependencies,omitempty"`                          // List of required plugin names
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Requirements) Reset() {
	*x = Requirements{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Requirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Requirements) ProtoMessage() {}

func (x *Requirements) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Requirements.ProtoReflect.Descriptor instead.
func (*Requirements) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{14}
}

func (x *Requirements) GetMinOriVersion() string {
	if x != nil {
		return x.MinOriVersion
	}
	return ""
}

func (x *Requirements) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

// PluginMetadata contains comprehensive plugin information
type PluginMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`               // Plugin name
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`         // Plugin version (semver)
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // Short description of the plugin
	License       string                 `protobuf:"bytes,4,opt,name=license,proto3" json:"license,omitempty"`         // e.g., "MIT", "Apache-2.0", "GPL-3.0"
	Repository    string                 `protobuf:"bytes,5,opt,name=repository,proto3" json:"repository,omitempty"`   // Source code repository URL
	Maintainers   []*Maintainer          `protobuf:"bytes,6,rep,name=maintainers,proto3" json:"maintainers,omitempty"`
	Platforms     []*Platform            `protobuf:"bytes,7,rep,name=platforms,proto3" json:"platforms,omitempty"`       // Supported platforms
	Requirements  *Requirements          `protobuf:"bytes,8,opt,name=requirements,proto3" json:"requirements,omitempty"` // Plugin requirements
	Tags          []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`                 // Plugin tags (normalized, e.g., "dev-tools", "audio")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginMetadata) Reset() {
	*x = PluginMetadata{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginMetadata) ProtoMessage() {}

func (x *PluginMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginMetadata.ProtoReflect.Descriptor instead.
func (*PluginMetadata) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{15}
}

func (x *PluginMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginMetadata) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *PluginMetadata) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *PluginMetadata) GetMaintainers() []*Maintainer {
	if x != nil {
		return x.Maintainers
	}
	return nil
}

func (x *PluginMetadata) GetPlatforms() []*Platform {
	if x != nil {
		return x.Platforms
	}
	return nil
}

func (x *PluginMetadata) GetRequirements() *Requirements {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *PluginMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// MetadataResponse contains plugin metadata
type MetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *PluginMetadata        `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Error message on failure (empty on success)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataResponse) Reset() {
	*x = MetadataResponse{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataResponse) ProtoMessage() {}

func (x *MetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataResponse.ProtoReflect.Descriptor instead.
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{16}
}

func (x *MetadataResponse) GetMetadata() *PluginMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MetadataResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// CompatibilityInfoResponse contains plugin compatibility information
type CompatibilityInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MinAgentVersion string                 `protobuf:"bytes,1,opt,name=min_agent_version,json=minAgentVersion,proto3" json:"min_agent_version,omitempty"` // Minimum ori-agent version required
	MaxAgentVersion string                 `protobuf:"bytes,2,opt,name=max_agent_version,json=maxAgentVersion,proto3" json:"max_agent_version,omitempty"` // Maximum ori-agent version supported
	ApiVersion      string                 `protobuf:"bytes,3,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`                  // Plugin API version
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompatibilityInfoResponse) Reset() {
	*x = CompatibilityInfoResponse{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompatibilityInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompatibilityInfoResponse) ProtoMessage() {}

func (x *CompatibilityInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompatibilityInfoResponse.ProtoReflect.Descriptor instead.
func (*CompatibilityInfoResponse) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{17}
}

func (x *CompatibilityInfoResponse) GetMinAgentVersion() string {
	if x != nil {
		return x.MinAgentVersion
	}
	return ""
}

func (x *CompatibilityInfoResponse) GetMaxAgentVersion() string {
	if x != nil {
		return x.MaxAgentVersion
	}
	return ""
}

func (x *CompatibilityInfoResponse) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

// WebPagesResponse contains the list of available web pages
type WebPagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pages         []string               `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"` // List of page paths (e.g., "marketplace", "settings")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebPagesResponse) Reset() {
	*x = WebPagesResponse{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebPagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebPagesResponse) ProtoMessage() {}

func (x *WebPagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebPagesResponse.ProtoReflect.Descriptor instead.
func (*WebPagesResponse) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{18}
}

func (x *WebPagesResponse) GetPages() []string {
	if x != nil {
		return x.Pages
	}
	return nil
}

// WebPageRequest contains the web page request parameters
type WebPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                                                                             // The requested path (e.g., "marketplace")
	Query         map[string]string      `protobuf:"bytes,2,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // URL query parameters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebPageRequest) Reset() {
	*x = WebPageRequest{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebPageRequest) ProtoMessage() {}

func (x *WebPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebPageRequest.ProtoReflect.Descriptor instead.
func (*WebPageRequest) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{19}
}

func (x *WebPageRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WebPageRequest) GetQuery() map[string]string {
	if x != nil {
		return x.Query
	}
	return nil
}

// WebPageResponse contains the web page content
type WebPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`                            // HTML or JSON content
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // MIME type (e.g., "text/html", "application/json")
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                                // Error message on failure (empty on success)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebPageResponse) Reset() {
	*x = WebPageResponse{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebPageResponse) ProtoMessage() {}

func (x *WebPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebPageResponse.ProtoReflect.Descriptor instead.
func (*WebPageResponse) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{20}
}

func (x *WebPageResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *WebPageResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *WebPageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ProtoFileAttachment represents a file attached to a plugin call (proto version)
// Note: Named ProtoFileAttachment to avoid conflict with pluginapi.FileAttachment
type ProtoFileAttachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // Original filename (e.g., "drums.wav")
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`       // MIME type (e.g., "audio/wav", "application/zip")
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`      // File size in bytes
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"` // Raw file content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoFileAttachment) Reset() {
	*x = ProtoFileAttachment{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoFileAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoFileAttachment) ProtoMessage() {}

func (x *ProtoFileAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoFileAttachment.ProtoReflect.Descriptor instead.
func (*ProtoFileAttachment) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{21}
}

func (x *ProtoFileAttachment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProtoFileAttachment) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProtoFileAttachment) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ProtoFileAttachment) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// AcceptsFilesResponse contains the list of accepted file types
type AcceptsFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AcceptedTypes []string               `protobuf:"bytes,1,rep,name=accepted_types,json=acceptedTypes,proto3" json:"accepted_types,omitempty"`  // MIME types or extensions (e.g., ".wav", "audio/wav")
	SupportsFiles bool                   `protobuf:"varint,2,opt,name=supports_files,json=supportsFiles,proto3" json:"supports_files,omitempty"` // True if plugin implements FileAttachmentHandler
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptsFilesResponse) Reset() {
	*x = AcceptsFilesResponse{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptsFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptsFilesResponse) ProtoMessage() {}

func (x *AcceptsFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptsFilesResponse.ProtoReflect.Descriptor instead.
func (*AcceptsFilesResponse) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{22}
}

func (x *AcceptsFilesResponse) GetAcceptedTypes() []string {
	if x != nil {
		return x.AcceptedTypes
	}
	return nil
}

func (x *AcceptsFilesResponse) GetSupportsFiles() bool {
	if x != nil {
		return x.SupportsFiles
	}
	return false
}

// CallWithFilesRequest contains arguments and file attachments for a tool call
type CallWithFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArgsJson      string                 `protobuf:"bytes,1,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"` // JSON-encoded tool arguments
	Files         []*ProtoFileAttachment `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`                       // File attachments
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallWithFilesRequest) Reset() {
	*x = CallWithFilesRequest{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallWithFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallWithFilesRequest) ProtoMessage() {}

func (x *CallWithFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallWithFilesRequest.ProtoReflect.Descriptor instead.
func (*CallWithFilesRequest) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{23}
}

func (x *CallWithFilesRequest) GetArgsJson() string {
	if x != nil {
		return x.ArgsJson
	}
	return ""
}

func (x *CallWithFilesRequest) GetFiles() []*ProtoFileAttachment {
	if x != nil {
		return x.Files
	}
	return nil
}

// ProtoOperationInfo describes a single operation and its parameters
type ProtoOperationInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                       // Operation name (e.g., "create_project")
	Parameters         []string               `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty"`                                           // Parameter names for this operation
	RequiredParameters []string               `protobuf:"bytes,3,rep,name=required_parameters,json=requiredParameters,proto3" json:"required_parameters,omitempty"` // Required parameter names
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProtoOperationInfo) Reset() {
	*x = ProtoOperationInfo{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoOperationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoOperationInfo) ProtoMessage() {}

func (x *ProtoOperationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoOperationInfo.ProtoReflect.Descriptor instead.
func (*ProtoOperationInfo) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{24}
}

func (x *ProtoOperationInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProtoOperationInfo) GetParameters() []string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ProtoOperationInfo) GetRequiredParameters() []string {
	if x != nil {
		return x.RequiredParameters
	}
	return nil
}

// OperationsResponse contains the list of operations with their parameters
type OperationsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Operations         []*ProtoOperationInfo  `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	SupportsOperations bool                   `protobuf:"varint,2,opt,name=supports_operations,json=supportsOperations,proto3" json:"supports_operations,omitempty"` // True if plugin implements OperationsProvider
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OperationsResponse) Reset() {
	*x = OperationsResponse{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationsResponse) ProtoMessage() {}

func (x *OperationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationsResponse.ProtoReflect.Descriptor instead.
func (*OperationsResponse) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{25}
}

func (x *OperationsResponse) GetOperations() []*ProtoOperationInfo {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *OperationsResponse) GetSupportsOperations() bool {
	if x != nil {
		return x.SupportsOperations
	}
	return false
}

var File_pluginapi_proto_tool_proto protoreflect.FileDescriptor

const file_pluginapi_proto_tool_proto_rawDesc = "" +
	"\n" +
	"\x1apluginapi/proto/tool.proto\x12\tpluginapi\"\a\n" +
	"\x05Empty\"o\n" +
	"\x0eToolDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12'\n" +
	"\x0fparameters_json\x18\x03 \x01(\tR\x0eparametersJson\"*\n" +
	"\vCallRequest\x12\x1b\n" +
	"\targs_json\x18\x01 \x01(\tR\bargsJson\"E\n" +
	"\fCallResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\tR\n" +
	"resultJson\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"+\n" +
	"\x0fVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\x8c\x01\n" +
	"\x13AgentContextRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vconfig_path\x18\x02 \x01(\tR\n" +
	"configPath\x12#\n" +
	"\rsettings_path\x18\x03 \x01(\tR\fsettingsPath\x12\x1b\n" +
	"\tagent_dir\x18\x04 \x01(\tR\bagentDir\"M\n" +
	"\x10SettingsResponse\x12#\n" +
	"\rsettings_json\x18\x01 \x01(\tR\fsettingsJson\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x97\x02\n" +
	"\x13ProtoConfigVariable\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12,\n" +
	"\x12default_value_json\x18\x06 \x01(\tR\x10defaultValueJson\x12\x1e\n" +
	"\n" +
	"validation\x18\a \x01(\tR\n" +
	"validation\x12\x18\n" +
	"\aoptions\x18\b \x03(\tR\aoptions\x12 \n" +
	"\vplaceholder\x18\t \x01(\tR\vplaceholder\"Z\n" +
	"\x17ConfigVariablesResponse\x12?\n" +
	"\vconfig_vars\x18\x01 \x03(\v2\x1e.pluginapi.ProtoConfigVariableR\n" +
	"configVars\"8\n" +
	"\x15ValidateConfigRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\tR\n" +
	"configJson\":\n" +
	"\x17InitializeConfigRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\tR\n" +
	"configJson\"@\n" +
	"\x0eConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xa2\x01\n" +
	"\n" +
	"Maintainer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\"\n" +
	"\forganization\x18\x03 \x01(\tR\forganization\x12\x18\n" +
	"\awebsite\x18\x04 \x01(\tR\awebsite\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x18\n" +
	"\aprimary\x18\x06 \x01(\bR\aprimary\"@\n" +
	"\bPlatform\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12$\n" +
	"\rarchitectures\x18\x02 \x03(\tR\rarchitectures\"Z\n" +
	"\fRequirements\x12&\n" +
	"\x0fmin_ori_version\x18\x01 \x01(\tR\rminOriVersion\x12\"\n" +
	"\fdependencies\x18\x02 \x03(\tR\fdependencies\"\xd7\x02\n" +
	"\x0ePluginMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\alicense\x18\x04 \x01(\tR\alicense\x12\x1e\n" +
	"\n" +
	"repository\x18\x05 \x01(\tR\n" +
	"repository\x127\n" +
	"\vmaintainers\x18\x06 \x03(\v2\x15.pluginapi.MaintainerR\vmaintainers\x121\n" +
	"\tplatforms\x18\a \x03(\v2\x13.pluginapi.PlatformR\tplatforms\x12;\n" +
	"\frequirements\x18\b \x01(\v2\x17.pluginapi.RequirementsR\frequirements\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\"_\n" +
	"\x10MetadataResponse\x125\n" +
	"\bmetadata\x18\x01 \x01(\v2\x19.pluginapi.PluginMetadataR\bmetadata\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x94\x01\n" +
	"\x19CompatibilityInfoResponse\x12*\n" +
	"\x11min_agent_version\x18\x01 \x01(\tR\x0fminAgentVersion\x12*\n" +
	"\x11max_agent_version\x18\x02 \x01(\tR\x0fmaxAgentVersion\x12\x1f\n" +
	"\vapi_version\x18\x03 \x01(\tR\n" +
	"apiVersion\"(\n" +
	"\x10WebPagesResponse\x12\x14\n" +
	"\x05pages\x18\x01 \x03(\tR\x05pages\"\x9a\x01\n" +
	"\x0eWebPageRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12:\n" +
	"\x05query\x18\x02 \x03(\v2$.pluginapi.WebPageRequest.QueryEntryR\x05query\x1a8\n" +
	"\n" +
	"QueryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\x0fWebPageResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"k\n" +
	"\x13ProtoFileAttachment\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\"d\n" +
	"\x14AcceptsFilesResponse\x12%\n" +
	"\x0eaccepted_types\x18\x01 \x03(\tR\racceptedTypes\x12%\n" +
	"\x0esupports_files\x18\x02 \x01(\bR\rsupportsFiles\"i\n" +
	"\x14CallWithFilesRequest\x12\x1b\n" +
	"\targs_json\x18\x01 \x01(\tR\bargsJson\x124\n" +
	"\x05files\x18\x02 \x03(\v2\x1e.pluginapi.ProtoFileAttachmentR\x05files\"y\n" +
	"\x12ProtoOperationInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"parameters\x18\x02 \x03(\tR\n" +
	"parameters\x12/\n" +
	"\x13required_parameters\x18\x03 \x03(\tR\x12requiredParameters\"\x84\x01\n" +
	"\x12OperationsResponse\x12=\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\x1d.pluginapi.ProtoOperationInfoR\n" +
	"operations\x12/\n" +
	"\x13supports_operations\x18\x02 \x01(\bR\x12supportsOperations2\x9e\b\n" +
	"\vToolService\x12<\n" +
	"\rGetDefinition\x12\x10.pluginapi.Empty\x1a\x19.pluginapi.ToolDefinition\x127\n" +
	"\x04Call\x12\x16.pluginapi.CallRequest\x1a\x17.pluginapi.CallResponse\x12:\n" +
	"\n" +
	"GetVersion\x12\x10.pluginapi.Empty\x1a\x1a.pluginapi.VersionResponse\x12C\n" +
	"\x0fSetAgentContext\x12\x1e.pluginapi.AgentContextRequest\x1a\x10.pluginapi.Empty\x12C\n" +
	"\x12GetDefaultSettings\x12\x10.pluginapi.Empty\x1a\x1b.pluginapi.SettingsResponse\x12I\n" +
	"\x11GetRequiredConfig\x12\x10.pluginapi.Empty\x1a\".pluginapi.ConfigVariablesResponse\x12M\n" +
	"\x0eValidateConfig\x12 .pluginapi.ValidateConfigRequest\x1a\x19.pluginapi.ConfigResponse\x12U\n" +
	"\x14InitializeWithConfig\x12\".pluginapi.InitializeConfigRequest\x1a\x19.pluginapi.ConfigResponse\x12<\n" +
	"\vGetMetadata\x12\x10.pluginapi.Empty\x1a\x1b.pluginapi.MetadataResponse\x12N\n" +
	"\x14GetCompatibilityInfo\x12\x10.pluginapi.Empty\x1a$.pluginapi.CompatibilityInfoResponse\x12<\n" +
	"\vGetWebPages\x12\x10.pluginapi.Empty\x1a\x1b.pluginapi.WebPagesResponse\x12E\n" +
	"\fServeWebPage\x12\x19.pluginapi.WebPageRequest\x1a\x1a.pluginapi.WebPageResponse\x12A\n" +
	"\fAcceptsFiles\x12\x10.pluginapi.Empty\x1a\x1f.pluginapi.AcceptsFilesResponse\x12I\n" +
	"\rCallWithFiles\x12\x1f.pluginapi.CallWithFilesRequest\x1a\x17.pluginapi.CallResponse\x12@\n" +
	"\rGetOperations\x12\x10.pluginapi.Empty\x1a\x1d.pluginapi.OperationsResponseB,Z*github.com/johnjallday/ori-agent/pluginapib\x06proto3"

var (
	file_pluginapi_proto_tool_proto_rawDescOnce sync.Once
	file_pluginapi_proto_tool_proto_rawDescData []byte
)

func file_pluginapi_proto_tool_proto_rawDescGZIP() []byte {
	file_pluginapi_proto_tool_proto_rawDescOnce.Do(func() {
		file_pluginapi_proto_tool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pluginapi_proto_tool_proto_rawDesc), len(file_pluginapi_proto_tool_proto_rawDesc)))
	})
	return file_pluginapi_proto_tool_proto_rawDescData
}

var file_pluginapi_proto_tool_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_pluginapi_proto_tool_proto_goTypes = []any{
	(*Empty)(nil),                     // 0: pluginapi.Empty
	(*ToolDefinition)(nil),            // 1: pluginapi.ToolDefinition
	(*CallRequest)(nil),               // 2: pluginapi.CallRequest
	(*CallResponse)(nil),              // 3: pluginapi.CallResponse
	(*VersionResponse)(nil),           // 4: pluginapi.VersionResponse
	(*AgentContextRequest)(nil),       // 5: pluginapi.AgentContextRequest
	(*SettingsResponse)(nil),          // 6: pluginapi.SettingsResponse
	(*ProtoConfigVariable)(nil),       // 7: pluginapi.ProtoConfigVariable
	(*ConfigVariablesResponse)(nil),   // 8: pluginapi.ConfigVariablesResponse
	(*ValidateConfigRequest)(nil),     // 9: pluginapi.ValidateConfigRequest
	(*InitializeConfigRequest)(nil),   // 10: pluginapi.InitializeConfigRequest
	(*ConfigResponse)(nil),            // 11: pluginapi.ConfigResponse
	(*Maintainer)(nil),                // 12: pluginapi.Maintainer
	(*Platform)(nil),                  // 13: pluginapi.Platform
	(*Requirements)(nil),              // 14: pluginapi.Requirements
	(*PluginMetadata)(nil),            // 15: pluginapi.PluginMetadata
	(*MetadataResponse)(nil),          // 16: pluginapi.MetadataResponse
	(*CompatibilityInfoResponse)(nil), // 17: pluginapi.CompatibilityInfoResponse
	(*WebPagesResponse)(nil),          // 18: pluginapi.WebPagesResponse
	(*WebPageRequest)(nil),            // 19: pluginapi.WebPageRequest
	(*WebPageResponse)(nil),           // 20: pluginapi.WebPageResponse
	(*ProtoFileAttachment)(nil),       // 21: pluginapi.ProtoFileAttachment
	(*AcceptsFilesResponse)(nil),      // 22: pluginapi.AcceptsFilesResponse
	(*CallWithFilesRequest)(nil),      // 23: pluginapi.CallWithFilesRequest
	(*ProtoOperationInfo)(nil),        // 24: pluginapi.ProtoOperationInfo
	(*OperationsResponse)(nil),        // 25: pluginapi.OperationsResponse
	nil,                               // 26: pluginapi.WebPageRequest.QueryEntry
}
var file_pluginapi_proto_tool_proto_depIdxs = []int32{
	7,  // 0: pluginapi.ConfigVariablesResponse.config_vars:type_name -> pluginapi.ProtoConfigVariable
	12, // 1: pluginapi.PluginMetadata.maintainers:type_name -> pluginapi.Maintainer
	13, // 2: pluginapi.PluginMetadata.platforms:type_name -> pluginapi.Platform
	14, // 3: pluginapi.PluginMetadata.requirements:type_name -> pluginapi.Requirements
	15, // 4: pluginapi.MetadataResponse.metadata:type_name -> pluginapi.PluginMetadata
	26, // 5: pluginapi.WebPageRequest.query:type_name -> pluginapi.WebPageRequest.QueryEntry
	21, // 6: pluginapi.CallWithFilesRequest.files:type_name -> pluginapi.ProtoFileAttachment
	24, // 7: pluginapi.OperationsResponse.operations:type_name -> pluginapi.ProtoOperationInfo
	0,  // 8: pluginapi.ToolService.GetDefinition:input_type -> pluginapi.Empty
	2,  // 9: pluginapi.ToolService.Call:input_type -> pluginapi.CallRequest
	0,  // 10: pluginapi.ToolService.GetVersion:input_type -> pluginapi.Empty
	5,  // 11: pluginapi.ToolService.SetAgentContext:input_type -> pluginapi.AgentContextRequest
	0,  // 12: pluginapi.ToolService.GetDefaultSettings:input_type -> pluginapi.Empty
	0,  // 13: pluginapi.ToolService.GetRequiredConfig:input_type -> pluginapi.Empty
	9,  // 14: pluginapi.ToolService.ValidateConfig:input_type -> pluginapi.ValidateConfigRequest
	10, // 15: pluginapi.ToolService.InitializeWithConfig:input_type -> pluginapi.InitializeConfigRequest
	0,  // 16: pluginapi.ToolService.GetMetadata:input_type -> pluginapi.Empty
	0,  // 17: pluginapi.ToolService.GetCompatibilityInfo:input_type -> pluginapi.Empty
	0,  // 18: pluginapi.ToolService.GetWebPages:input_type -> pluginapi.Empty
	19, // 19: pluginapi.ToolService.ServeWebPage:input_type -> pluginapi.WebPageRequest
	0,  // 20: pluginapi.ToolService.AcceptsFiles:input_type -> pluginapi.Empty
	23, // 21: pluginapi.ToolService.CallWithFiles:input_type -> pluginapi.CallWithFilesRequest
	0,  // 22: pluginapi.ToolService.GetOperations:input_type -> pluginapi.Empty
	1,  // 23: pluginapi.ToolService.GetDefinition:output_type -> pluginapi.ToolDefinition
	3,  // 24: pluginapi.ToolService.Call:output_type -> pluginapi.CallResponse
	4,  // 25: pluginapi.ToolService.GetVersion:output_type -> pluginapi.VersionResponse
	0,  // 26: pluginapi.ToolService.SetAgentContext:output_type -> pluginapi.Empty
	6,  // 27: pluginapi.ToolService.GetDefaultSettings:output_type -> pluginapi.SettingsResponse
	8,  // 28: pluginapi.ToolService.GetRequiredConfig:output_type -> pluginapi.ConfigVariablesResponse
	11, // 29: pluginapi.ToolService.ValidateConfig:output_type -> pluginapi.ConfigResponse
	11, // 30: pluginapi.ToolService.InitializeWithConfig:output_type -> pluginapi.ConfigResponse
	16, // 31: pluginapi.ToolService.GetMetadata:output_type -> pluginapi.MetadataResponse
	17, // 32: pluginapi.ToolService.GetCompatibilityInfo:output_type -> pluginapi.CompatibilityInfoResponse
	18, // 33: pluginapi.ToolService.GetWebPages:output_type -> pluginapi.WebPagesResponse
	20, // 34: pluginapi.ToolService.ServeWebPage:output_type -> pluginapi.WebPageResponse
	22, // 35: pluginapi.ToolService.AcceptsFiles:output_type -> pluginapi.AcceptsFilesResponse
	3,  // 36: pluginapi.ToolService.CallWithFiles:output_type -> pluginapi.CallResponse
	25, // 37: pluginapi.ToolService.GetOperations:output_type -> pluginapi.OperationsResponse
	23, // [23:38] is the sub-list for method output_type
	8,  // [8:23] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pluginapi_proto_tool_proto_init() }
func file_pluginapi_proto_tool_proto_init() {
	if File_pluginapi_proto_tool_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluginapi_proto_tool_proto_rawDesc), len(file_pluginapi_proto_tool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pluginapi_proto_tool_proto_goTypes,
		DependencyIndexes: file_pluginapi_proto_tool_proto_depIdxs,
		MessageInfos:      file_pluginapi_proto_tool_proto_msgTypes,
	}.Build()
	File_pluginapi_proto_tool_proto = out.File
	file_pluginapi_proto_tool_proto_goTypes = nil
	file_pluginapi_proto_tool_proto_depIdxs = nil
}
